### ISSUE TITLE
How-to checklist

### ISSUE THREAD

**Issue by amandaharlin** [techlahoma/user-group-docs#4]
this isn't finished, but i'll post the checklist. i'd like to make this into a form that people interact with (because the 'or' option doesn't translate well without the radio buttons).
- [x] Find a need for a user group to fill
- [x] Find interest in the community
- [ ] Join Techlahoma
- [ ] Have a Code of Conduct
  - [ ] Use the Techlahoma CoC, modify an existing CoC, or create your own  
- [ ] Use a 'super user' account for everything
  - [ ] Create a 'super user' group email account
  - [ ] Use that email for everything: twitter, meetup, g+, etc
- [ ] Decide on your meeting place
  - [ ] Techlahoma provides user groups with a free meeting space at Prototek 
  - [ ] Find a meeting space, agree to their insurance forms for meeting at the space, and pay to reserve it it
    - [ ] Small groups (12 people) can meet at the 404. Small, Med, Large groups can meet at the Library, the Paramount, or inside a business.
- [ ] Decide when you'll meet
  - [ ] Use the Techlahoma Date/Time Availability Page to see what's open
- [ ] Recruit Organizers and Volunteers
  - [ ] Have _at least_ three volunteers to help out the group
  - [ ] Decide on primary focuses for individual volunteers
- [ ] Have a group website
  - [ ] Host it in a maintainable space
  - [ ] Train your volunteers on how to update the website
  - [ ] Use Hexo (Techlahoma provides groups with training on an easy to setup and maintainable blogging platform, Hexo)
    - [ ] Pick a theme that Techlahoma created, create your own, or use an existing theme
  - [ ] Add your group's info to the site
    - [ ] About
    - [ ] Date & Time
    - [ ] Location
    - [ ] Social Media
    - [ ] Contact
- [ ] Pick an email provider
  - [ ] Use MailChimp 
    - [ ] View Techlahoma's MailChimp training if needed
  - [ ] Use Meetup as a mailing option
- [ ] Ask your community what they want to learn about
  - [ ]  Ask potential speakers if they'd talk at your group 
  - [ ] Consider preparing talks to give in case of necessity
  - [ ] Agree to never skip your regularly scheduled meeting. Have a 'town tall' meeting at your group if a speaker is unavailable. Just don't lose that momentum.
- [ ] Decide if you'll record the event or live stream
  - [ ] Use Techlahoma's recording gear by meeting at Prototek. (Techlahoma provides user groups with a dedicated computer, software, and video cameras for recording speakers and events)
  - [ ] Buy a computer, computer screen, software, video cameras
